export const RecipesStrings = {
  RECIPES_LIST_HEADER: "PRZEPISY",
  INGREDIENTS_LIST_HEADER: "SKŁADNIKI",
  INGREDIENTS_SEARCH_INPUT_PLACEHOLDER: "Szukaj składników",
  INGREDIENTS_UPDATE_RECIPES: "Zaktualizuj przepisy",
  ADD_RECIPE_HEADER: "Dodaj przepis",
  ADD_RECIPE_NAME_INPUT_PLACEHOLDER: "Nazwa przepisu",
  ADD_RECIPE_SOURCE_INPUT_PLACEHOLDER: "Zródło przepisu",
  ADD_RECIPE_SAVE: "Zapisz przepis"
}
